name: Deploy Static Website to EC2 (Apache)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from your GitHub repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH key to access your EC2 instance
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    # Step 3: Install and Setup Apache
    - name: Install and Setup Apache
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Install Apache (Amazon Linux)
          if [ -f /etc/system-release ] && grep -q "Amazon Linux" /etc/system-release; then
            sudo yum install httpd -y
            sudo systemctl start httpd
            sudo systemctl enable httpd
          # Install Apache (Ubuntu)
          elif [ -f /etc/lsb-release ]; then
            sudo apt update
            sudo apt install apache2 -y
            sudo systemctl start apache2
            sudo systemctl enable apache2
          fi
        EOF

    # Step 4: Copy files to the EC2 instance
    - name: Deploy to EC2
      run: |
        rsync -avz --delete ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.REMOTE_PATH }}

    # Step 5: Restart Apache Web Server
    - name: Restart Apache
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          if [ -f /etc/system-release ] && grep -q "Amazon Linux" /etc/system-release; then
            sudo systemctl restart httpd
          elif [ -f /etc/lsb-release ]; then
            sudo systemctl restart apache2
          fi
        EOF
