name: Deploy Static Website to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH key for authentication
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 3: Deploy the static website to the EC2 instance
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Navigate to the web server directory
            cd /var/www/html
            
            # Remove old files (if any)
            sudo rm -rf *
            
            # Copy the new files from the repository
            sudo mkdir -p 2133_moso_interior
            cd 2133_moso_interior
            sudo cp -r /home/${{ secrets.EC2_USER }}/2133_moso_interior/* .

            # Restart the web server (if needed)
            sudo systemctl restart nginx || sudo systemctl restart httpd
